Jan-IngenHousz-Institute/open-jii

.gitattributes, infrastructure/env/dev/main.tf, infrastructure/env/dev/variables.tf, infrastructure/modules/cloudfront/cloudfront.md, infrastructure/modules/cloudfront/main.tf, infrastructure/modules/cloudfront/outputs.tf, infrastructure/modules/cloudfront/variables.tf, infrastructure/modules/docusaurus-s3/docusaurus-s3.md, infrastructure/modules/docusaurus-s3/main.tf, infrastructure/modules/docusaurus-s3/outputs.tf, infrastructure/modules/docusaurus-s3/variables.tf, package.json
This pull request includes several changes to the Terraform infrastructure and documentation to improve the security and organization of the S3 and CloudFront modules. The key changes involve replacing the CloudFront Origin Access Identity (OAI) with Origin Access Control (OAC) and updating relevant configurations and documentation.
* [`infrastructure/env/dev/main.tf`](diffhunk://#diff-f6672b4c785f679251f4f9dbd2e79d208b1486eb63bcb0db45be92c90197d13eL1-R13): Replaced the CloudFront Origin Access Identity (OAI) with the new Origin Access Control (OAC) and updated the module configurations accordingly.
* [`infrastructure/modules/cloudfront/main.tf`](diffhunk://#diff-2025f0d6792ee81272f0113b32da3889ec4aa5a879fee18eef95947ac513e52fR1-R13): Added a new resource for CloudFront Origin Access …
=> feat(infrastructure): switches cloudfront distribution from OAI (legacy) to OAC

infrastructure/env/dev/backend.tf, infrastructure/env/dev/main.tf, infrastructure/env/dev/variables.tf, infrastructure/modules/iot-core/iot-core.md, infrastructure/modules/iot-core/main.tf, infrastructure/modules/iot-core/outputs.tf, infrastructure/modules/iot-core/variables.tf, infrastructure/modules/kinesis/kinesis.md, infrastructure/modules/kinesis/main.tf, infrastructure/modules/kinesis/outputs.tf, infrastructure/modules/kinesis/variables.tf, infrastructure/modules/s3/main.tf, infrastructure/modules/s3/variables.tf, infrastructure/modules/timestream/timestream.md, infrastructure/modules/timestream/variables.tf
This pull request introduces significant updates to the infrastructure configuration, primarily focusing on integrating Kinesis Data Streams and refining the existing IoT Core and Timestream setups. The changes enhance real-time data processing capabilities and improve modularity.
* Added a new Kinesis module to provision AWS Kinesis Data Streams for real-time data processing (`infrastructure/modules/kinesis/kinesis.md`, `infrastructure/modules/kinesis/main.tf`, `infrastructure/modules/kinesis/outputs.tf`, `infrastructure/modules/kinesis/variables.tf`). [[1]](diffhunk://#diff-fe3576e785ba8a610ddbb53ac371a1ea75b30c26500e9b40776cff9f4867dbefR1-R63) [[2]](diffhunk://#diff-816230bc543f92cdbd9f7e0b0365265eff51a1237a9fa15b1c124a44fd8cbf54R1-R5) …
=> feat(infrastructure): Implements Kinesis Data Stream for IoT Core topic consumption

infrastructure/env/dev/main.tf, infrastructure/env/dev/variables.tf, infrastructure/modules/databricks/job/main.tf, infrastructure/modules/databricks/job/variables.tf, infrastructure/notebooks/tasks/experiment_monitor_task.py, infrastructure/notebooks/tasks/experiment_orchestrator_task.py
This pull request includes significant updates to the infrastructure and orchestration of Databricks jobs and pipelines. The changes introduce new modules, variables, and tasks to enhance the management and monitoring of data processing workflows.
* [`infrastructure/env/dev/main.tf`](diffhunk://#diff-f6672b4c785f679251f4f9dbd2e79d208b1486eb63bcb0db45be92c90197d13eR34-R38): Added new Databricks providers and updated configurations for various modules, including `kinesis`, `databricks_workspace`, `databricks_catalog`, and `centrum_pipeline`. Also introduced new modules for `kinesis_ingest_cluster`, `experiment_orchestrator_cluster`, `kinesis_ingest_job`, and `experiment_orchestrator_job`. [[1]](diffhunk://#diff-f6672b4c785f679251f4f9dbd2e79d208b1486eb63bcb0db45be92c90197d13eR34-R38) …
=> feat(databricks): adds DLT orchestration, real-time ingest cont. Job, task for creating experiment pipelines

.gitignore, apps/tools/multispeq_mqtt_interface/src/multispeq_mqtt_interface/cli/commands.py, apps/tools/multispeq_mqtt_interface/src/multispeq_mqtt_interface/cli/interface.py, apps/tools/multispeq_mqtt_interface/src/multispeq_mqtt_interface/cli/prompts.py, apps/tools/multispeq_mqtt_interface/src/multispeq_mqtt_interface/device/device.py, apps/tools/multispeq_mqtt_interface/src/multispeq_mqtt_interface/utils/config.py
This pull request introduces several enhancements to the `multispeq_mqtt_interface` tool, particularly focusing on adding support for continuous measurement and plant metadata management. The most important changes include adding new methods for continuous measurement, incorporating plant metadata into the data payload, and updating the configuration to store plant data.
**Continuous measurement and plant metadata management:**
* [`apps/tools/multispeq_mqtt_interface/src/multispeq_mqtt_interface/cli/commands.py`](diffhunk://#diff-8b32be7221e685d53b982703a50b33fbd52f790eab2c7edf39b6cc9d6f2729dcR161-R277): Added a new method `continuous_publish` for continuously measuring and publishing data every 6 seconds until stopped. This method includes user prompts for plant data and saves it for …
=> feat(tooling): extends MultispeQ Interface Tool to handle continuous measuring (development & testing purposes)

.github/ISSUE_TEMPLATE/user_story.md
This pull request introduces a new Agile User Story Template in the `.github/ISSUE_TEMPLATE` directory. The template is designed to standardize the creation of user stories, ensuring they align with the INVEST criteria and include necessary details for clarity and completeness.
Key changes:
* Added a new file `user_story.md` with an Agile User Story Template. This template includes sections for the user story description, acceptance criteria, definition of ready (DoR), definition of done (DoD), dependencies, risks, and additional context.
=> chore: Adds user story github issue template

.github/actions/blt/action.yml
This pull request includes changes to the `.github/actions/blt/action.yml` file to update the setup process for Node.js and pnpm. The most important changes involve the removal of Corepack setup steps and the addition of a specific action to set up pnpm.
Improvements to the setup process:
* [`.github/actions/blt/action.yml`](diffhunk://#diff-5add2b4469a302a6125b9cc24c7f0990bbdcad55d294536b6a0f1505ae783ce3L23-L35): Replaced the Corepack setup steps with the `pnpm/action-setup@v4` action to streamline the pnpm setup process.
* [`.github/actions/blt/action.yml`](diffhunk://#diff-5add2b4469a302a6125b9cc24c7f0990bbdcad55d294536b6a0f1505ae783ce3L23-L35): Simplified the Node.js setup by removing the `fetch-depth` parameter and ensuring the cache is set for pnpm.
=> feat(cicd): Sets up pnpm via github action

apps/node-red/package.json, pnpm-lock.yaml
This pull request includes the addition of a new `package.json` file for the `node-red` application. This file defines the basic metadata and dependencies required for the application.
Key additions:
* [`apps/node-red/package.json`](diffhunk://#diff-76ef19d5a5649cc514608fd9a482bf33ca1cdddf9adddd42e91019005f150741R1-R16): Added a new `package.json` file that includes the application name, version, main entry point, scripts, and dependencies.
=> feat: add node-red app

.github/actions/blt/action.yml, .github/workflows/deployment-template.yml, .github/workflows/pr.yml
This pull request introduces several enhancements to the GitHub Actions workflow, focusing on identifying and processing affected projects more efficiently. The key changes include adding new inputs and outputs, modifying the build, lint, and test steps to handle affected projects, and updating the deployment workflow to use these new outputs.
* **New Inputs and Outputs:**
- Added `artifact_retention` and `base` inputs to `.github/actions/blt/action.yml`.
- Updated outputs to include `affected_apps` and `has_affected_apps` instead of individual project build statuses.
* **Build, Lint, and Test Steps:**
- Introduced a new step to identify affected projects based on the provided base reference.
- Modified build, lint, and test steps to run only if there are affected projects.
* **Artifact …
=> feat(cicd): improves cicd process by ensuring only affected are built and deployed

apps/backend/.env.test, apps/backend/Dockerfile, apps/backend/docker-compose.yml, apps/backend/package.json, apps/backend/src/app.module.ts, apps/backend/src/health/health.controller.ts, apps/backend/src/health/health.module.ts, packages/database/.env.default, packages/database/docker-compose.yml, packages/database/drizzle.config.ts, packages/database/package.json, packages/validator/package.json, packages/validator/tsconfig.json
This pull request introduces several significant updates to the backend and database configurations, Docker setup, and package improvements. Key changes include the addition of a Dockerized environment for the backend, a health check endpoint, updated database configurations, and adjustments to package scripts and build processes.
* **Dockerfile for Backend**: Added a multi-stage Dockerfile to build and run the backend application efficiently, including dependency installation, build steps, and production configuration.
* **Docker Compose for Backend**: Introduced a `docker-compose.yml` file for orchestrating the backend and database services, including health checks and network setup.
* **Health Check Endpoint**: Added a `HealthModule` with a `HealthController` to expose a `/health` …
=> feat(backend): adds Dockerfile & local docker-compose

apps/backend/package.json, apps/backend/src/experiments/application/pipes/experiment-filter.pipe.ts, apps/backend/src/experiments/core/models/experiment-members.model.ts, apps/backend/src/experiments/core/models/experiment.model.ts, apps/backend/src/experiments/utils/fp-utils.spec.ts, apps/backend/src/experiments/utils/fp-utils.ts, packages/database/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
Now that catalog allows direct sharing of libraries without packaging,
this simplifies usage by removing unnecessary abstraction layers and
leveraging zod directly for improved clarity and maintainability.
- Closes #
- Related to #
=> chore: use zod directly via catalog instead of shared lib

infrastructure/env/dev/main.tf, infrastructure/env/dev/variables.tf, infrastructure/modules/cognito/README.md, infrastructure/modules/cognito/main.tf, infrastructure/modules/cognito/outputs.tf, infrastructure/modules/cognito/variables.tf
This pull request introduces a new AWS Cognito module to enable unauthenticated IoT devices to securely connect to AWS IoT Core and publish MQTT messages. Key changes include adding the Cognito module to the development environment, defining its variables, outputs, and main implementation, and providing comprehensive documentation for its usage.
* **Development Environment Integration**:
- Added a `cognito` module to `infrastructure/env/dev/main.tf` for managing the Cognito Identity Pool. (`[infrastructure/env/dev/main.tfR68-R73](diffhunk://#diff-f6672b4c785f679251f4f9dbd2e79d208b1486eb63bcb0db45be92c90197d13eR68-R73)`)
- Introduced a new variable `iot_cognito_identity_pool_name` in `infrastructure/env/dev/variables.tf` for naming the Cognito Identity Pool. …
=> feat(infra): adds cognito identity pool to support mobile mqtt auth

apps/backend/src/main.ts, apps/web/app/openjii/experiments/[id]/page.tsx, apps/web/app/openjii/experiments/page.tsx, apps/web/components/app-layout.tsx, apps/web/components/create-experiment.tsx, apps/web/components/edit-experiment.tsx, packages/ui/package.json, packages/ui/src/components/index.ts, packages/ui/src/components/toast.tsx, packages/ui/src/components/toaster.tsx, packages/ui/src/hooks/index.ts, packages/ui/src/hooks/use-toast.ts, pnpm-lock.yaml
This adds improved layout and toasts to the create experiment flow.
=> feat(web): create experiment (layout fixes, toast)

apps/docs/package.json
Docusaurus automatically opens a browser window every time you start it up in dev mode. This is annoying and this PR changes that behaviour.
=> feat(docs): Do not open browser window on startup

.github/workflows/deployment-template_OLD.yml, .github/workflows/pr.yml
Initial code for PR workflow fix , check for artifacts, referencing outputs from blt action. Also modify "old" dev template to include only TF plan and apply.
- Related to #251 
- Change "old" development template
- Initial code for fix of the artifacts downloading
=> fix(infra): Initial code for PR workflow fix

apps/web/app/openjii/experiments/page.tsx, apps/web/components/list-experiments.tsx, apps/web/lib/tsr.ts, packages/auth/src/config.ts, packages/auth/src/express.ts, packages/auth/src/next.ts
- Closes #207 
- Related to #207
=> feat: includes jwt creds in requests via tsr

infrastructure/modules/iam-oidc/data.tf, infrastructure/modules/iam-oidc/main.tf
- [ X ] Refactor
Just change of a arn for the iam-oidc hardcoded arn to use data src. and vars
- Closes #256 
- [ X ] My code follows the project's style guidelines
- [ X ] My changes generate no new warnings
- [ X ] I have reviewed my own code
=> fix(infra): iam-oidc arn-256

.github/workflows/deployment-template.yml, infrastructure/modules/iam-oidc/main.tf
- [ X ] Feature
Update the Cognito Pools permissions for Github deploy policy
- Closes #260 
- [ X ] My code follows the project's style guidelines
- [ X ] My changes generate no new warnings
=> feat(infra): Updating the Cognito Pools perm. for deploy policy

infrastructure/env/dev/main.tf, infrastructure/modules/iam-oidc/main.tf, infrastructure/modules/iam-oidc/variables.tf
Fix small infra TF code issue with a var and passing values.
- [ X ] Bug Fix
- Closes #264
=> fix(infra): Bugfix/tf typo-264

.github/workflows/pr.yml
- [ X ] Refactor
- Related to #251 
-Add Role & Region in pr.yml when calling tofu action
=> feat(infra): Add Role & Region in pr.yml when calling tofu action

.github/workflows/pr.yml
- [ X ] Feature
Add temp dispatch to PR workflow for debug purposes
- Related to #251
=> feat(cdcd): Add temp dispatch to PR workflow

apps/web/app/openjii/experiments/new/page.tsx, apps/web/app/openjii/experiments/page.tsx, apps/web/components/app-sidebar.tsx, apps/web/components/edit-experiment.tsx, apps/web/components/experiment-table-rows.tsx, apps/web/components/list-experiments.tsx, apps/web/hooks/experiment/useExperiments/useExperiments.ts, apps/web/providers/QueryProvider.tsx, apps/web/util/date.ts, apps/web/util/searchParams.ts, package.json, packages/database/package.json
This pull request introduces several enhancements and refactors across the codebase, focusing on improving experiment management, user experience, and code maintainability. Key changes include the addition of filtering and sorting capabilities for experiments, improved error handling, and the introduction of reusable utility functions. Below is a summary of the most important changes grouped by theme:
* Added filtering and status selection for experiments in `ListExperiments`, allowing users to filter by ownership and experiment status. (`apps/web/components/list-experiments.tsx`, [apps/web/components/list-experiments.tsxL3-L56](diffhunk://#diff-d3ff8c22f0ad9d5a73d9596d8d5427fe383fc02825103ec2fd97524a5e903b59L3-L56))
* Introduced a new `ExperimentTableContent` component to handle …
=> feat: list experiments

.github/actions/bpd/action.yml, .github/actions/btn/action.yml, .github/workflows/build-and-push.yml
Initial commit of build and test node and build and push docker image for the backend. Only actions.
- Related to #270
=> feat(cicd): Feat/cicd backend 270

apps/web/providers/QueryProvider.tsx
=> fix: restructure mutation error handling with MutationCache

apps/web/app/[locale]/platform/layout.tsx, packages/ui/src/components/sidebar.tsx
Adds a max width to the platform UI
=> fix: adjust layout component to center content and update sidebar inset to use div instead of main

apps/docs/package.json, pnpm-lock.yaml
Updated docusaurus from 3.7.0 to 3.8.1 due to build issues
- Closes #
- Related to #
-
-
=> fix: Updated docusaurus from 3.7.0 to 3.8.1 due to build issues

apps/web/components/new-experiment/new-experiment.tsx
Fixed missing success toast for create experiment to make the user experience consistent with the update form.
=> fix(web): Fix success toast for new experiment

apps/backend/package.json, apps/backend/src/common/utils/drizzle-error-utils.spec.ts, apps/backend/src/common/utils/drizzle-error-utils.ts, apps/backend/src/common/utils/fp-utils.spec.ts, apps/backend/src/common/utils/fp-utils.ts, packages/database/package.json, packages/database/src/index.ts, pnpm-lock.yaml
This PR introduces comprehensive type-safe error handling utilities for Drizzle ORM operations and updates all
Drizzle packages to their latest versions.
- **Type-safe Drizzle error utilities** (`drizzle-error-utils.ts`)
- PostgreSQL error type guards and extraction functions
- Comprehensive error code constants for constraint violations, data type errors, and schema errors
- Convenience functions for common error types (unique constraint, foreign key, not null, etc.)
- Proper DrizzleQueryError import support with updated packages
- **Enhanced repository error mapping** (`fp-utils.ts`)
- Better PostgreSQL error detection using error codes
- Fallback to message-based detection for compatibility
- Support for nested Drizzle error structures
- **Complete test coverage** …
=> feat: add comprehensive Drizzle ORM error handling utilities and update drizzle packages

apps/web/app/[locale]/platform/layout.tsx, apps/web/app/[locale]/register/page.tsx, apps/web/app/actions/auth.ts, apps/web/components/registration-form.tsx, apps/web/hooks/useCreateUserProfile.ts, apps/web/lib/auth.ts, infrastructure/modules/opennext-cloudfront/main.tf, packages/auth/src/config.ts, packages/auth/src/types.ts
Improves the user registration flow by removing the mandatory logout requirement and implementing proper session management for newly registered users.
- **Streamlined Registration Process**
- Eliminates forced logout after registration completion
- Automatically updates user session with registered status
- Redirects users to intended destination via callback URL support
- Adds proper authentication guards to registration page
- **Enhanced Session Management**
- Implements session update functionality using NextAuth's `unstableUpdate`
- Added type-safe session validation with custom type guards
- Proper JWT token updates when registration status changes
- Session persistence across registration completion
- **Authentication Flow Improvements**
- Added `handleRegister` action to update …
=> feat(auth): registration flow without forced logout

infrastructure/env/dev/main.tf, infrastructure/env/dev/variables.tf, infrastructure/modules/databricks/catalog/main.tf, infrastructure/modules/databricks/catalog/variables.tf, infrastructure/modules/databricks/job/main.tf, infrastructure/modules/databricks/job/variables.tf, infrastructure/modules/databricks/pipeline/main.tf, infrastructure/modules/databricks/pipeline/variables.tf, infrastructure/modules/databricks/secret_scope/main.tf, infrastructure/modules/databricks/secret_scope/outputs.tf, infrastructure/modules/databricks/secret_scope/variables.tf, infrastructure/modules/databricks/service_principal/main.tf, infrastructure/modules/databricks/service_principal/outputs.tf, infrastructure/modules/databricks/service_principal/variables.tf, infrastructure/modules/databricks/workspace/main.tf, infrastructure/modules/databricks/workspace/outputs.tf, infrastructure/modules/databricks/workspace/variables.tf, infrastructure/notebooks/tasks/experiment_status_update_task.py
This PR enhances the Databricks infrastructure with service principal integration, secret management, and experiment pipeline provisioning capabilities. The changes replace the manual experiment orchestration approach with an automated, webhook-based system that improves security and scalability.
- **Service Principal Management**
- Added Databricks service principal creation and management module
- Implemented permissions and access controls for service principals
- Replaced hardcoded credentials with dynamic, terraform-managed service principal
- **Secret Scope Management**
- Created new Databricks secret scope module for secure credential management
- Implemented granular ACL controls for secrets
- Added webhook authentication for secure backend communication
- **Pipeline …
=> feat(infra): integrates databricks experiment provisioning infra with status update & waf rate_limit update

.github/workflows/main-coverage.yml
Use HEAD commit SHA directly instead of HEAD^2 for squash merge compatibility
-
-
=> fix(ci): handle squash merges in main coverage workflow

apps/web/app/[locale]/layout.tsx, apps/web/app/__tests__/layout.test.tsx, apps/web/app/__tests__/locale-layout.test.tsx, apps/web/app/__tests__/not-found.test.tsx, apps/web/app/layout.tsx, apps/web/app/not-found.tsx, packages/i18n/locales/de-DE/common.json, packages/i18n/locales/en-US/common.json, packages/i18n/locales/nl-NL/common.json, pnpm-lock.yaml, tooling/vitest-config/package.json, tooling/vitest-config/src/configs/ui-config.ts
=> feat: implement custom 404 Not Found page with locale detection and internationalized messages
